# Generated by Django 5.0.7 on 2024-08-02 11:25

import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('instructions', djrichtextfield.models.RichTextField(max_length=10000)),
                ('ingredients', djrichtextfield.models.RichTextField(max_length=10000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='cakes/')),
                ('image_alt', models.CharField(max_length=100)),
                ('cake_type', models.CharField(choices=[('classic', 'Classic'), ('fruit', 'Fruit Cake'), ('cupcake', 'Cupcake'), ('cheesecake', 'Cheesecake')], default='classic', max_length=50)),
                ('flavor', models.CharField(choices=[('vanilla', 'Vanilla'), ('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('lemon', 'Lemon'), ('coffee', 'Coffee')], default='vanilla', max_length=50)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
